import os

DATA_DIRECTORY = './data'
MODEL_DIRECTORY = './models'

EPOCHS = 5
BATCH_SIZE = 32
LEARNING_RATE = 0.0001
MAX_SEQ_LENGTH = 512
MAX_RESPONSE_LENGTH = 50

BEARER_TOKEN = ''
CONSUMER_KEY = ''
CONSUMER_SECRET = ''
ACCESS_TOKEN = ''
ACCESS_TOKEN_SECRET = ''
CLIENT_ID = ''
CLIENT_SECRET = ''